SERENITY-1491-migrate-and-reinforce-notebook-functions-to-python-sdk
cloudwall/serenity.sdk.python pull request #11
Opened 2022-08-18 05:23 UTC by Jose-cloudwallcapital

2022-08-18 11:52 UTC, mtzavellas-cw requested changes

2022-08-18 11:52 UTC, mtzavellas-cw commented on notebooks/demo_notebook.ipynb
> +    "client.total_risk['volatility']"
Are we supposed to use `totalrisk` or `total_risk`?

2022-08-18 12:00 UTC, kdowney-cloudwallcapital commented on src/python/serenity_sdk/client.py
> +        print(self.risk_attribution.keys())
SDK code should never do a print() -- this is a display choice which should stay in the notebook.

2022-08-18 12:06 UTC, kdowney-cloudwallcapital requested changes
There are a number of design issues here that need to be fixed. The refactoring should not invalidate most of the code or tests, but I don't think we should push out in this state.

2022-08-18 12:06 UTC, kdowney-cloudwallcapital commented on src/python/serenity_sdk/client.py
> +        self.assetcov_response = self.call_api('risk', '/asset/covariance', params=params)
This is not good design. You are making the client, which is stateless, stateful by storing responses. What you should do is introduce response *objects* which can carry state, and then return it.

2022-08-18 12:06 UTC, kdowney-cloudwallcapital commented on src/python/serenity_sdk/client.py
> +        self.factorcov_response = self.call_api('risk', '/factor/covariance', params=params)
Related to design: by passing in a Dict in a client method with no validation at all, this function really adds no value at all. Ideally parameters should be a typed request class (one per call, maybe with hierarchy) but at bare minimum this dictionary should be validated for bad or missing parameters.

2022-08-18 12:06 UTC, kdowney-cloudwallcapital commented on src/python/serenity_sdk/client.py
> +            raise APIException('Please, provide a portfolio')
You default to None but then assert to ensure portfolio is non-null. This does not make sense.

2022-08-18 12:06 UTC, kdowney-cloudwallcapital commented on src/python/serenity_sdk/client.py
> +        print(self.ids)
Do not print in SDK code.

2022-08-18 12:06 UTC, kdowney-cloudwallcapital commented on src/python/serenity_sdk/client.py
> +        return self.total_risk
As above, these things are not a property of a client. These are properties of a response object.

2022-08-18 16:26 UTC, ilya-kulyatin requested changes
This also needs to update the requirements.txt and the setup.cfg with the new SDK version number. I'll push this next, feel free to change.

Also note that there was a PR that never got merged, and it contained the new version of the demo notebook. Could you please check it and the tables that are missing?

2022-08-18 16:26 UTC, ilya-kulyatin commented on src/python/serenity_sdk/client.py
> +    def liquidity_factor(self):
This should actually be in the Notebook, because it's just a way for the user to see how a certain metric can be derived from other components (I've done it to help with the user's understanding of what some metrics represent).

2022-08-18 16:26 UTC, ilya-kulyatin commented on src/python/serenity_sdk/client.py
> +    def portfolio_weights(self):
See my comment on the liquidity_factor method below: this is also just an alternative way of extracting what the API gives us. This should stay in the Notebook.

2022-08-18 16:26 UTC, ilya-kulyatin commented on src/python/serenity_sdk/client.py
> +    def contribution_risk_by_sector(self):
Needs same formatting work as `sector_factor_exposure`.

2022-08-18 16:36 UTC, ilya-kulyatin commented
The updated demo notebook is actually here in this PR: https://github.com/cloudwall/serenity.sdk.python/blob/cfca571159d586c92e53adbd570abd566fa885b8/notebooks/demo_notebook.ipynb

It has tables that have been pushed to the new docs on the developer portal. The best way is to copy that notebook to this repo, and add the missing client calls.

2022-08-19 14:52 UTC, ilya-kulyatin requested changes

2022-08-19 14:52 UTC, ilya-kulyatin commented on src/python/serenity_sdk/client.py
> +    def liquidity_factor(self):
I think this one is still to remove.

2022-08-19 20:09 UTC, closed without merging