Serenity 1491 migrate and reinforce notebook functions to python sdk
cloudwall/serenity.sdk.python pull request #13
Opened 2022-08-19 20:23 UTC by Jose-cloudwallcapital

2022-08-19 22:47 UTC, kdowney-cloudwallcapital requested changes

2022-08-19 22:47 UTC, kdowney-cloudwallcapital commented on notebooks/README.md
> +cd /notebooks
Not sure where all my comments disappeared to.

This line is wrong: you are providing an absolute path and cd'ing into a directory that you're already in. Remove.

2022-08-20 10:14 UTC, ilya-kulyatin commented on notebooks/README.md
> +cd /notebooks
My bad, I added this line.

2022-08-27 11:53 UTC, closed without merging

2022-08-27 11:54 UTC, kdowney-cloudwallcapital commented
Being re-done