Serenity 2515 create sample notebook in sdk to demo derivatives api usage continued
cloudwall/serenity.sdk.python pull request #63
Opened 2022-12-12 22:20 UTC by youngsuklee-cloudwall

2022-12-12 22:28 UTC, youngsuklee-cloudwall commented
Hi. I updated derivative demo notebooks and create a place holder for Greek test.

2022-12-12 22:56 UTC, kdowney-cloudwallcapital requested changes
Please remove all "validation" code -- the SDK is public, it's not meant for the kinds of things you are doing here. Remove all the BS helper code, remove the greek validation notebook entirely. This is what the serenity.testbed (internal) project is for.

2022-12-13 15:35 UTC, youngsuklee-cloudwall commented
Updated derivative demo notebooks with more tests. 
Added plotly for a 3D plot.

2022-12-13 15:53 UTC, kdowney-cloudwallcapital approved these changes

2022-12-13 15:53 UTC, merged