SERENITY-3727-portfolio-wallet-sync-cronjob-in-org-services
cloudwall/serenity.sdk.python pull request #90
Opened 2023-04-20 22:09 UTC by swang-cc

2023-04-22 06:12 UTC, mtzavellas-cw requested changes

2023-04-22 06:12 UTC, mtzavellas-cw commented on src/python/serenity_types/account/core.py
> +    account_id: UUID
The account id is part of the path, there is no need to add it in the request object

2023-04-22 11:59 UTC, swang-cc commented on src/python/serenity_types/account/core.py
> +    account_id: UUID
Will change it. bwt. I followed the portfolio sdk.

2023-04-24 13:57 UTC, swang-cc commented on src/python/serenity_types/account/core.py
> +    account_id: UUID
More evidences that I am following Portfolio SDK api.

![Screen Shot 2023-04-24 at 09 56 27](https://user-images.githubusercontent.com/105223464/234018361-7e0ad774-56b2-4037-8bdb-53fbef20633a.png)
![Screen Shot 2023-04-24 at 09 56 37](https://user-images.githubusercontent.com/105223464/234018362-d79ad4cb-36f4-44a1-9b7c-55dfb0f0aaae.png)

2023-04-25 01:39 UTC, mtzavellas-cw commented on src/python/serenity_types/account/core.py
> +    account_id: UUID
Yep, you're right, the SDK type is slightly different to make it more convenient to use.

2023-04-27 21:37 UTC, swang-cc commented
renaming branch, raise a new pr. closed this one.

2023-04-27 21:37 UTC, closed without merging